# Generated by Django 5.1.7 on 2025-10-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default-avatar.png', upload_to='profile_pics/'),
        ),
    ]
